### ISSUE TITLE
Disable gapless audio?

### ISSUE THREAD

**Issue by DBTaylor** [vanilla-music/vanilla#1138]
- Vanilla Music Version (Settings -> About): 1.1.0
- Android Version: 12
- Phone vendor / model:
- Application was downloaded from (use `[x]`):
  - [x ] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [ x] NA / Don't know.

## Description
Is there a way to disable gapless?

I'm on a Pixel 6. Every time a new track starts, it is silent. Restarting the track will make it play. There have been similar issues with people using black player on Pixel 6, and disabling gapless fixes the issue.

## Steps to reproduce the issue
Let a track end. The next track plays, but there is no sound.

**Comment by yaomtc** [comment]
Same here, happening on a Pixel 6a.

**Comment by yaomtc** [comment]
Seems to be an issue with ReplayGain? I turned it off and it's stopped happening.

**Comment by el3030anon** [comment]
I have the same issue on my new Pixel 7. Music Apps with Gapples Playback have the same issue but you can turn it off, then it is okay. ReplayGain doesnt fix it for me. Would really appreciate a gapless-playback-option. Thanks a thousand for this wonderful app...

**Comment by yaomtc** [comment]
Update, it happened again. Can confirm that disabling Replay Gain didn't fix the issue for me either. Doesn't happen every time. Seems to be kinda rare.

**Comment by adrian-bl** [comment]
I am confused: So are we suspecting the issue to be Replay Gain or Gapless?

**Comment by el3030anon** [comment]
Sorry for the confusion, Adrian. I suspect the problem lies with gapless, since replay gain doesnt fix it. Also it may be a device-specific problem, since it happend to me after switching to a Pixel (and others here have Pixels too). After i ran into the problem i tested a lot of other apps an on some the problem could be solved by switching off gapless. Right now i am using Musicolet which has gapless playback enabled and still plays the next song. Indeed confusing. Sorry again, if this is not helpful. I still hope i can switch back to Vanilla in some time, it is  my favorite music player...

**Comment by adrian-bl** [comment]
If gapless is at fault, then that is very much a firmware issue with the phone - maybe Musicolet works because it was fixed in the meantime?

I could add an Option to disable the feature - but would rather not if not needed

**Comment by el3030anon** [comment]
I dunno, the thing with gapples audio is just a more or less educated guess, it seems worth a shot to me after looking through the issues. But i tried out today  with the latest nightly build (nice changes to the interface) and the problem persists (playback works fine, but on some albums the next track is silent, it affects newer albums more so than older albums, this is indeed quite strange). It is quite the same as described in  #1111 though. Maybe it is Pixel-related, i use a Pixel 7 with GrapheneOS, there are a few Pixels in the comments. Thanks for the effort, and maybe you can offer other payment-options for donations, i dont use BC... Thanks!

**Comment by bart3005** [comment]
I have the same issue on a pixel 7 pro. If I play an album on next track it silent. Gapless is nice if listening to mixed music so be a shame to have to disable it

**Comment by adrian-bl** [comment]
Ok, i hacked something up to disable gapless: Could someone give http://android.eqmx.net/android/vanilla/VanillaMusic-nightly.apk a try? (Installs under a different package name and shows up as 'Vanilla Nightly' in the launcher, so no need to uninstall the existing version).

This build has a version to disable gapless playback in Settings -> Audio.

*It is not disabled by default, so please go to settings and disable it* after installing - and report back if it helps.

**Comment by el3030anon** [comment]
Hello Adrian, thanks a lot, for me its working. Tried out 2 Albums that previously always played muted after one song and if i disable gapless its playing continuous (Pixel 7 w. GrapheneOS). Thats wonderful news, thank you!!!

**Comment by bart3005** [comment]
Seems to have fixed the issue for me on stock ROM on a Pixel 7 Pro.

**Comment by adrian-bl** [comment]
Ok, thanks a lot for the feedback!

I just pushed a commit to allow the string in the options to be translated, and given that this was pretty simple to implement, lets just keep it as is (as an option)
