### ISSUE TITLE
Songs without metadata disappeared after 1.0.47 update

### ISSUE THREAD

**Issue by refi64** [vanilla-music/vanilla#517]
I have a crapton of MP3s in Download/Music that don't have any metadata. After I updated, they all disappeared. Now comes the weird part: the metadata-less ogg files in the same folder appeared, except they have no title:

[![Screenshot_20170118-211627.png](https://s5.postimg.org/673ba89hj/Screenshot_20170118_211627.png)](https://postimg.org/image/m5c10d3pf/)

It gets even weirder, though; I think Vanilla is still counting the songs in its # of tracks, because this seems unusually high to be excluding all my metadata-less ones:

[![Screenshot_20170118-212216.png](https://s5.postimg.org/8cxm4qcxz/Screenshot_20170118_212216.png)](https://postimg.org/image/mjdczynsz/)

**Comment by kirbyfan64** [comment]
Oof, looks like songs with a title but nothing else broke, too; take a look at this screenshot:

[![Screenshot_20170118-212725.png](https://s5.postimg.org/na635qq6f/Screenshot_20170118_212725.png)](https://postimg.org/image/hlzseultv/)

If I select the top, empty "artist", I end up here:

[![Screenshot_20170118-212841.png](https://s5.postimg.org/7d7b90xs7/Screenshot_20170118_212841.png)](https://postimg.org/image/pg0e08tmr/)

Selecting the sole, err, album leads me here:

[![Screenshot_20170118-212844.png](https://s5.postimg.org/q6t460w07/Screenshot_20170118_212844.png)](https://postimg.org/image/xa0zln1fn/)

Some of these further down actually have artist metadata showing, but they're still under the blank artist.

I also get the same exact results when I open up the `<No artist>` entry instead, which makes me wonder why there are even two...

**Comment by kirbyfan64** [comment]
Man, this just keeps getting better. Wake up today, and **BAM**, the two songs without a title somehow grabbed cover art from an entirely separate folder:

[![Screenshot_20170119-102933.png](https://s5.postimg.org/4burno5qf/Screenshot_20170119_102933.png)](https://postimg.org/image/bru19gtfn/)

And, no, these songs have nothing to do with Miku... ?

**Comment by Adonai** [comment]
@adrian-bl , do we somehow interoperate with native media library in our media-db?

**Comment by adrian-bl** [comment]
> Now comes the weird part: the metadata-less ogg files in the same folder appeared, except they have no title:

They *do* have a title - the title just happens to be an empty string :-)

We really should relex the 'no tags - no index' rule: I implemented the isTagged() check  because the mediascanner somehow managed to pick up whatsapp databases (thinking, it was a valid MP3 file).

> Selecting the sole, err, album leads me here:
> Some of these further down actually have artist metadata showing, but they're still under the blank artist.

This will then *only* filter by album - the Artist is not taken into account. So you'll simply end up with a list of albums which have no artist set.

> Man, this just keeps getting better. Wake up today, and BAM, the two songs without a title somehow 
> grabbed cover art from an entirely separate folder:

They are also in the 'No Album' group: Cover artwork gets cached by album.
So at one point, vanilla music stumbled across a song with ALBUM=No Album which has the Miku cover and cached it (where the source is either an embedded cover or a front.jpg in a folder) - this cover is then inherited by all other songs.

But that's nothing new and has been like this since forever.

> do we somehow interoperate with native media library in our media-db?

We use it for quick scans and to check for embedded artwork. But we never read metadata from it.

**Comment by kirbyfan64** [comment]
Ah, that all makes more sense now...

**Comment by adrian-bl** [comment]
I made the check for audio files less trict with commit https://github.com/vanilla-music/vanilla/commit/a6442948fca44c5ccf04d6782e1958eea877ee94 - this is already included in the latest nightly version and we should therefore be able to display untagged songs (again).

**Comment by kirbyfan64** [comment]
:+1:

**Comment by Allanitomwesh** [comment]
Hi @adrian-bl
This issue persists, but you closed where I posted about it (#511) so I'll just continue here 
So with the ~.48 update, the issue is abit better but not fixed
The music in ogg now plays as <no artist> <no album> IF I play it from the file manager. 
It does not detect album art from the folder I played it from and instead tacks on a random one
The player does not detect the music automatically still, and still skips it in a scan. 

So a bit better but still not ideal.

**Comment by kirbyfan64** [comment]
> It does not detect album art from the folder I played it from and instead tacks on a random one

*looks up*

https://github.com/vanilla-music/vanilla/issues/517#issuecomment-273836035

> The player does not detect the music automatically still, and still skips it in a scan.

I usually have to do a full scan...

**Comment by Allanitomwesh** [comment]
Upon closer inspection it is not a random art.
It is the art from the only track with <artist><no album> in my collection

**Comment by adrian-bl** [comment]
Artwork is always grouped by Album, so if you have multiple tracks with no album, you end uo with random artwork.

How do you add the music to the device? If you have to do a *full/slow* scab, then we didn't find the missing files in androids media db.

(Full scan = recursive scan of filesystem, normal scan = sync with android mediadb)

That said: i think i broke newpipe again.

**Comment by Allanitomwesh** [comment]
The music is in my SD Card with my other albums in the music folder. It just happens that when I converted this particular album to ogg the tags didn't remain (couldn't find it in FLAC) 
It is an album with a cover.jpg in the folder 
So I know the artist, the album,etc

**Comment by Allanitomwesh** [comment]
It would also be good if the player didn't put all the untagged tracks in brackets

**Comment by adrian-bl** [comment]
> The music in ogg now plays as IF I play it from the file manager.
> It does not detect album art from the folder I played it from and instead tacks on a random one

Oh, good catch: This should be fixed via cc930c3dbbc0be029b66df6a3cc7333243142c0d - Unindexed files got the albumId '0' which might have end up getting a cover.

But its really strange that we are unable to pick up these songs: Did you do a full rescan or a normal one?
If you did a full scan: Could you send me yet another sample file to adrian@blinkenlights.ch ? This looks like our tagreader somehow fails.

> It would also be good if the player didn't put all the untagged tracks in brackets

Agreed, fixed in 3c15eca5e6691eb1febadf86dae6c0f768328c5a

**Comment by adrian-bl** [comment]
I somehow lost track about this bug report, so what should be fixed here exactly?

Just as a note: The current nightly build should have

* M4A fixed
* Has an option to group-albums-by-folder
* Does not use artwork for unindexed files

**Comment by Allanitomwesh** [comment]
It should not pick up tracks that are 5 secs or less. The scan picked up the Hangouts and Facebook message tones. 
It should not put unindexed tracks in brackets
It should detect them automatically and not need a manual scan to find them.

**Comment by adrian-bl** [comment]
> It should not pick up tracks that are 5 secs or less. The scan picked up the Hangouts and Facebook 
> message tones.

I have a couple of albums with < 5 sec sound tracks, so we shouldn't ignore them - but picking up ringtones and stuff is not ok. At which folder are they located? (We already blacklist /Ringtones/)

>  It should not put unindexed tracks in brackets

That's fixed in the nightly


> It should detect them automatically and not need a manual scan to find them.

That is what we try to do :-)
Can you describe some steps on how to reproduce the issue? I don't really see this issue on my device - but it might be possible that some other version of android handles MTP changes in a different way

**Comment by Allanitomwesh** [comment]
I think the detection is fine on .48
However, today I manually tagged the migos album, but strangely they are still bracketed even though they automatically moved out of "not artist"

**Comment by adrian-bl** [comment]
Looking at the screenshot you sent me it seems that the file has no TITLE Tag, so it shows up as <filename>.

(The <> was removed after the 1.0.48 release, so only the nightly version wouldnt add brackets)

**Comment by Allanitomwesh** [comment]
I was pretty certain I tagged them right. Anyway I'll report back after the update

**Comment by adrian-bl** [comment]
Closing this bug as 1.0.49 is about to be released and should fix these issues.
